SELECT G1.ID
FROM ECOLI_DATA G1
    JOIN ECOLI_DATA G2 ON G1.PARENT_ID = G2.ID
    JOIN ECOLI_DATA G3 ON G2.PARENT_ID = G3.ID
WHERE G2.PARENT_ID IS NOT NULL
    AND G3.PARENT_ID IS NULL
ORDER BY G1.ID