WITH DAYS AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, C.CAR_TYPE,
           DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
           CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE NULL
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT DAYS.HISTORY_ID,
       ROUND(DAYS.DAILY_FEE * DAYS.DURATION * 
             (1 - IFNULL(D.DISCOUNT_RATE / 100, 0)), 0) AS FEE
FROM DAYS
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
        ON DAYS.DURATION_TYPE = D.DURATION_TYPE AND DAYS.CAR_TYPE = D.CAR_TYPE
ORDER BY FEE DESC, DAYS.HISTORY_ID DESC;
