SELECT AP.APNT_NO,
       P.PT_NAME,
       P.PT_NO,
       D.MCDP_CD,
       D.DR_NAME,
       AP.APNT_YMD
FROM APPOINTMENT AP
    JOIN PATIENT P ON P.PT_NO = AP.PT_NO
    JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
WHERE AP.APNT_YMD LIKE '2022-04-13%' AND AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD